name: Generate PR with Claude Code

on:
  issues:
    types:
      - labeled

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    # Only run if the label name includes 'ai-pr' and an issue number is available
    if: contains(github.event.label.name, 'ai-pr') && github.event.issue.number != null
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Generate PR with AI
        uses: WillBooster/gen-pr@v2
        with:
          # required options
          issue-number: ${{ github.event.issue.number }}
          # optional options
          coding-tool: claude-code
          claude-code-extra-args: '--allowedTools Bash Edit Write'
          planning-model: bedrock/us.anthropic.claude-opus-4-20250514-v1:0
          reasoning-effort: high
          repomix-extra-args: "--compress --remove-empty-lines --include 'src/**/*.ts'"
          test-command: 'yarn check-for-ai'
          max-test-attempts: 5
        env:
          ANTHROPIC_MODEL: 'us.anthropic.claude-opus-4-20250514-v1:0'
          ANTHROPIC_SMALL_FAST_MODEL: 'us.anthropic.claude-3-5-haiku-20241022-v1:0'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
          CLAUDE_CODE_USE_BEDROCK: 1
