name: Generate PR with Aider and Gemini 2.5 Pro (example)

on:
  issues:
    types:
      - labeled
  workflow_dispatch:

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    # Only run if the label name includes 'ai-pr' and an issue number is available
    if: contains(github.event.label.name, 'ai-pr') && github.event.issue.number != null
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Generate PR with AI
        uses: WillBooster/gen-pr@v2
        with:
          # required options
          issue-number: ${{ github.event.issue.number }}
          # optional options
          planning-model: gemini/gemini-2.5-pro
          reasoning-effort: high
          repomix-extra-args: "--compress --remove-empty-lines --include 'src/**/*.ts'"
          aider-extra-args: '--model gemini/gemini-2.5-pro --edit-format diff-fenced --no-gitignore'
          test-command: 'yarn check-for-ai'
          max-test-attempts: 5
        env:
          # for Amazon (Bedrock)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
          # for Google (AI Studio)
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # for Google (Vertex AI)
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          # for OpenAI
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # for Azure OpenAI
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          # for Anthropic
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # for Claude Code
          ANTHROPIC_MODEL: 'us.anthropic.claude-opus-4-20250514-v1:0'
          ANTHROPIC_SMALL_FAST_MODEL: 'us.anthropic.claude-3-5-haiku-20241022-v1:0'
          CLAUDE_CODE_USE_BEDROCK: 1
          # for gh commands
          GH_TOKEN: ${{ secrets.PUBLIC_GH_BOT_PAT }}
