name: Generate PR with Aider and Gemini 2.5 Pro (example)

on:
  issues:
    types:
      - labeled
  workflow_dispatch:

permissions:
  contents: write # for pushing commits and branches
  issues: write # for creating PRs
  pull-requests: write # for creating PRs

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    # Only run if the label name includes 'ai-pr' / 'easy' and an issue number is available
    if: (contains(github.event.label.name, 'ai-pr') || contains(github.event.label.name, 'easy')) && github.event.issue.number != null
    steps:
      - uses: actions/checkout@v4
      # Set up an environment for AI coding tools
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      # Set up user settings on Git (optional)
      # - name: Set up user settings on Git
      #   run: |
      #     git config user.name "WillBooster Bot"
      #     git config user.email "bot@willbooster.com"
      - name: Generate PR with AI
        uses: WillBooster/gen-pr@v2
        with:
          # required options
          issue-number: ${{ github.event.issue.number }}
          # optional options
          planning-model: gemini/gemini-2.5-flash
          reasoning-effort: high
          repomix-extra-args: "--compress --remove-empty-lines --include 'src/**/*.ts'"
          aider-extra-args: '--model gemini/gemini-2.5-flash --edit-format diff-fenced --no-gitignore'
          test-command: 'yarn check-for-ai'
          max-test-attempts: 5
        env:
          # for planning models and Aider
          ## OpenAI
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ## Anthropic
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ## Amazon (Bedrock)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
          ## Google (AI Studio)
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ## Google (Vertex AI)
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          ## Azure OpenAI
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          ## OpenRouter
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          ## Ollama (optional)
          OLLAMA_BASE_URL: ${{ secrets.OLLAMA_BASE_URL }}
          OLLAMA_API_KEY: ${{ secrets.OLLAMA_API_KEY }}

          # for coding tools
          ## Claude Code
          ANTHROPIC_MODEL: 'us.anthropic.claude-opus-4-20250514-v1:0'
          ANTHROPIC_SMALL_FAST_MODEL: 'us.anthropic.claude-3-5-haiku-20241022-v1:0'
          CLAUDE_CODE_USE_BEDROCK: 1

          # for gh (required for creating PRs)
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
